# This is a basic workflow to help you get started with Actions

name: Update calendar

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: ['master']
    paths: 'generate-calendar.py'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs commands using the runners shell
    - name: Run the calendar generation
      run: |
        python -m pip install -r requirements.txt
        python generate-calendar.py # This file reads a few json files and then creates a set of html files in the doc folder
    - name: Commit files # transfer the new calendar
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add rt-rota.ics
        git commit -m "Updating the repository with GitHub"
        git push
